run_sidekiq.sh

Added run_sidekiq.sh to allow the deployment to run sidekiq in a container

Added run_sidekiq.sh to allow the deployment to run sidekiq

---

app/commands/base_command.rb
app/commands/build_representative_command.rb
app/commands/build_respondent_command.rb
app/commands/build_response_command.rb
app/commands/serial_sequence_command.rb
app/services/command_service.rb
spec/factories/json/json_command_factory.rb
spec/factories/json/json_response_factory.rb
spec/services/command_service_spec.rb
spec/support/factory_bot.rb
spec/support/json_factory_nodes.rb

Minor refactoring mainly around the factories and the ability to specify async in commands

Minor refactoring mainly around the factories

---

.gitignore
app/services/claim_file_builder/render_to_file.rb
spec/support/landing_folder_support/file_objects/et1_txt_file.rb
spec/support/landing_folder_support/file_objects/et1a_txt_file.rb
spec/support/landing_folder_support/file_objects/et3_txt_file.rb
spec/support/matchers/be_valid_et1_claim_text.rb
spec/support/matchers/be_valid_et1a_claim_text.rb

All ethos text files now windows style cr/lf line endings

All ethos text files now windows style cr/lf line endings

---

app/commands/build_response_command.rb
spec/commands/build_response_command_spec.rb
spec/requests/create_response_spec.rb

Added office phone number to response metadata

RST-1217 Added office phone number to response metadata

---

config/environments/development.rb
config/environments/production.rb

Bug fix - incorrectly used ENV.get instead of ENV.fetch in development and production environments

Bug fix - incorrectly used ENV.get

---

db/migrate/20180721164447_reconfigure_role_permissions_again.rb
db/migrate/20180722080012_add_lockable_to_admin_users.rb
db/structure.sql

Data migration for role permissions as first attempt didnt work
Added lockable columns for admin users to allow account to be locked

Data migration for role permissions as first attempt didnt work

---

config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

Replace etsystem@justice.gsi with no-replay@digital.justice

Fix_ET3_From_Email_Address

---

Gemfile
Gemfile.lock
config/sidekiq.yml

Added sidekiq failures gem to allow us to see failures

Added sidekiq failures gem to allow us to see failures

---

Gemfile
Gemfile.lock
spec/requests/v2/get_acas_certificate_spec.rb
vendor/gems/et_acas_api/app/services/et_acas_api/acas_api_service.rb
vendor/gems/et_acas_api/spec/factories/soap/soap_valid_acas_response_factory.rb
vendor/gems/et_acas_api/spec/support/aes_encryption.rb

ACAS API can now handle unicode characters in the data coming back from acas

ACAS API can now handle unicode characters

---

app/services/claim_file_builder/build_response_pdf_file.rb
spec/support/landing_folder_support/file_objects/et3_pdf_file.rb

ET3 PDF now has the submitted at date

ET3 PDF now has the submitted at date

---

Dockerfile
run.sh
run_sidekiq.sh
supervisor.conf
supervisor_awslogs.conf

None
None
- Logging changes - Setup supervisor to keep logging process alive

Preparation for release v2.0.1

---

awslogs.conf

This is a clone of #90 which I closed due to a Travis issue. Approved by @cakeben and @garytaylor on that PR.

Re-instate missing conf file

---

.travis.yml

This is @garytaylor's code from #104 extracted so we can put it in place sooner.

Fix Travis DB Build Failure

---

Gemfile.lock

Updated rack  due to vulnerability

RST-1515 API - Update rack gem to 2.0.6 due to vulnerability

---

app/commands/build_primary_respondent_command.rb
app/commands/create_reference_command.rb
app/types/address_hash_type.rb
app/types/stripped_string_type.rb
config/initializers/active_model_types.rb
spec/commands/build_primary_respondent_command_spec.rb
spec/requests/v2/request_reference_numbers_spec.rb

This PR makes the API a little more robust by removing spaces from address details - as this affected the post code lookup

Rst 1627 postcode bug

---

Gemfile
Gemfile.lock

Added the azure_env_secrets gem ready for azure

RST-1748 API (Azure) - Configure to use the azure_env_secrets gem

---

README.md
config/initializers/sidekiq.rb

Sidekiq redis config now acceps redis password

Sidekiq redis config now acceps redis password

---

spec/requests/v2/create_claim_spec.rb
spec/requests/v2/create_response_spec.rb
spec/support/landing_folder_support/file_objects/base_pdf_file.rb
spec/support/landing_folder_support/file_objects/base_pdf_section.rb
spec/support/landing_folder_support/file_objects/et1_pdf_file.rb
spec/support/landing_folder_support/file_objects/et3_pdf_file.rb
spec/support/landing_folder_support/staging_folder.rb

Performance improvements mainly to speed up tests, but this also improves the application performance slightly

Performance improvements

---

app/controllers/api/v2/build_blobs_controller.rb
app/controllers/api/v2/claims/build_claims_controller.rb
app/controllers/api/v2/diversity/build_diversity_responses_controller.rb
app/controllers/api/v2/references/create_references_controller.rb
app/controllers/api/v2/respondents/build_responses_controller.rb
app/controllers/concerns/cache_command_results.rb
app/models/command.rb
db/migrate/20190401204615_enable_pgcrypto.rb
db/migrate/20190401204745_create_commands.rb
db/structure.sql
spec/requests/v2/build_blob_spec.rb
spec/requests/v2/create_claim_spec.rb
spec/requests/v2/create_diversity_response_spec.rb
spec/requests/v2/create_response_spec.rb
spec/requests/v2/request_reference_numbers_spec.rb

This PR implements duplicate command detection.  It works at controller level only

RST-1383 - Duplicate command detection

---

Dockerfile
azure-pipelines.yml

Adding Azure Pipeline Devops functionality

---

azure-pipelines.yml

Adding conditions to pipeline

---

Dockerfile
README.md
azure-pipelines.yml

Adding manual brach build and ping.json fix

---

azure-pipelines.yml

Fixing build pipline test job

---

db/migrate/20190718073101_add_multiples_to_ccd_manchester_external_system.rb
db/seeds.rb

Adds the seed data to setup ccd export for multiples
RST-1930
```
[ ] Yes
[X] No
```

Added new setting for multiples into seed data

---

azure-pipelines.yml

remove skipping build when triggered manually

---

config/initializers/active_storage.rb

RST-1935
Configured active storage to expire in 10 days
```
[ ] Yes
[X] No
```

Configured active storage to expire in 10 days

---

db/migrate/20190814114741_correct_manchester_external_system.rb
db/migrate/20190814115312_add_glasgow_external_system.rb
db/seeds.rb
db/structure.sql

Updated seed for ccd

---

db/seeds.rb

Minor seed fix
```
[ ] Yes
[X] No
```

Removed structure.sql - no longer needed in git

---

db/migrate/20190910151238_add_remaining_ccd_offices.rb
db/seeds.rb

RST-2152
Added remaining offices to database for ccd
```
[ ] Yes
[X] No
```

RST-2152 (API) - Setup external systems for remaining offices (CCD)

---

Gemfile
Gemfile.lock
app/event_handlers/claim_export_feedback_received_handler.rb
app/event_handlers/claim_export_succeeded_handler.rb
app/jobs/trigger_event_job.rb
app/models/export.rb
app/models/export_event.rb
config/initializers/event_handlers.rb
db/migrate/20190930064423_create_export_events.rb
db/migrate/20190930073725_add_export_feedback_queue_to_external_systems.rb
db/migrate/20191001070626_add_external_data_to_exports.rb
db/migrate/20191002075439_add_progress_messages_to_export_events.rb
db/migrate/20191002075518_add_progress_messages_to_exports.rb
db/schema.rb
spec/event_handlers/claim_export_feedback_received_handler_spec.rb
spec/event_handlers/claim_export_succeeded_handler_spec.rb
spec/factories/export_factory.rb
spec/jobs/trigger_event_job_spec.rb
spec/requests/v2/export_claims_spec.rb

RST-2197
This PR makes small changes to the way data is exported to the exporters (i.e. ccd exporter) to allow for updating of progress / status by the exporter
```
[ ] Yes
[ ] No
```

Rst 2197 export states

---

db/migrate/20191007065212_allow_nil_state_in_export_events.rb
db/migrate/20191007065552_allow_nil_percent_complete_in_export_events.rb

This PR adds the migration files which were accidentally not committed as part of the last release
```
[ ] Yes
[X] No
```

These migrations were missed from the release today

---

app/commands/build_response_command.rb
spec/commands/build_response_command_spec.rb
spec/requests/v2/create_response_spec.rb

Changes made to get access to the office_email.
```
[ ] Yes
[ X] No
```

Changes made to have access to the office_email for ET3

---

app/event_handlers/prepare_claim_handler.rb
app/models/claim.rb
app/models/concerns/stored_file_base64_import.rb
app/models/uploaded_file.rb
spec/factories/json/json_address_factory.rb
spec/factories/json/json_respondent_factory.rb
spec/requests/v2/create_claim_spec.rb
spec/requests/v2/get_acas_certificate_spec.rb
spec/support/et_exporter_support/exported_data.rb
spec/support/fake_acas_server.rb

RST-2382
Adds acas file to exported output
```
[ ] Yes
[X] No
```

RST-2382 ACAS - Added background acas processing when claim arrives

---

config/application.rb

RST-2817 Claim confirmation handler now uses gov uk notify

---

app/event_handlers/prepare_claim_handler.rb

…n of claim rather than export
```
[ ] Yes
[ ] No
```

RST-2914 Renaming of rtf and csv files are now done during prep

---

app/commands/base_command.rb
app/commands/build_response_command.rb
app/models/response.rb
db/migrate/20201023053014_add_office_id_to_responses.rb
db/migrate/20201023053043_populate_office_id_in_responses.rb
db/schema.rb
spec/commands/build_response_command_spec.rb
spec/factories/response_factory.rb
spec/support/email_support/gov_uk_notify_email_objects/new_claim_email_en.rb

RST-2889 Added office relationship to responses

---

app/commands/build_primary_respondent_command.rb
app/services/build_claim_pdf_file_service.rb
spec/factories/json/json_respondent_factory.rb
spec/factories/respondent_factory.rb
spec/requests/v2/create_claim_spec.rb
spec/services/build_claim_pdf_file_service_spec.rb
spec/support/landing_folder_support/file_objects/et1_pdf_file/respondents_details_section.rb
spec/support/messaging/et1-pdf-v2-cy.yml
spec/support/messaging/et1-pdf-v2-en.yml
vendor/assets/pdf_forms/et1-v2-cy.yml
vendor/assets/pdf_forms/et1-v2-en.yml

RST-2924 Populating the acas exemption reason in the pdf form

---

db/migrate/20201113104003_migrate_commands_with_no_root_object_again.rb
db/schema.rb

RST-2905 Re migrating commands with no root object

---

app/jobs/assign_root_object_to_commands_job.rb

RST-2905 Correctly named background job

---

app/services/concerns/pdf_builder/multi_template.rb
spec/services/build_response_pdf_file_service_spec.rb
spec/support/landing_folder_support/file_objects/et3_pdf_file/respondent_section_v1.rb
spec/support/landing_folder_support/file_objects/et3_pdf_file_v1.rb

RST-2998 Allow for re generation of response pdf files
```
[ ] Yes
[X] No
```

RST-2998 Allow for re generation of response pdf files

---

app/commands/rebuild_response_additional_information_file_command.rb
spec/requests/v2/repair_response_spec.rb

RST-2905 Repairing of files with lost attachments didnt work
```
[ ] Yes
[X] No
```

RST-2905 Repairing of files with lost attachments didnt work

---

db/migrate/20201123101230_remove_unwanted_exports_from_atos_secondary.rb
db/schema.rb

RST-2905 Added migration to tidy up exports that are no longer needed

---

db/migrate/20201203163632_repair_uploaded_file_325810.rb
db/schema.rb

RST-3039 Repairing a damaged uploaded file - had expired for some reason
```
[ ] Yes
[ ] No
```

RST-3039 Repairing a damaged uploaded file - had expired for some reason

---

azure-pipelines.yml

Updated pool for build and push tasks

---

Dockerfile

RST-3311 (ECM) Added shared-mime-info to dockerfile

---

app/mailers/feedback_mailer.rb
config/environments/development.rb
config/environments/test.rb
spec/support/email_support/email_objects/new_feedback_email_html.rb
spec/support/email_support/email_objects/new_feedback_email_text.rb

HOTFIX Changed from address in feedback mailer

---

db/migrate/20210727053825_add_manually_actioned_to_claims.rb
db/schema.rb

RST-3453 Added manually_actioned column to claims table

---

db/migrate/20210728074000_configure_role_permissions_for_action_claims.rb
db/schema.rb

RST-3453 Added permission entry

---

app/event_handlers/prepare_claim_handler.rb
app/models/uploaded_file.rb
spec/requests/v2/create_claim_spec.rb
spec/support/email_support/gov_uk_notify_email_objects/new_claim_email_en.rb

Changes made so that the confirmation email sent to the user is using the same RTF file name as the one uploaded.
```
[ ] Yes
[ X] No
```

RST-3005 Changes made to use the same rtf file name uploaded by a user.

---

Gemfile
Gemfile.lock
app/event_handlers/claim_email_handler.rb
config/application.rb
spec/support/email_support/gov_uk_notify_email_objects/new_claim_email_cy.rb
spec/support/email_support/gov_uk_notify_email_objects/new_claim_email_en.rb
spec/support/email_support/govuk_notify_emails_sent_monitor.rb
spec/support/gov_fake_notify.rb
spec/support/messaging/et1-email-v1-cy.yml
spec/support/messaging/et1-email-v1-en.yml

RST-2958 Integrated gov_fake_notify gem

---

app/services/concerns/pdf_builder/rendering.rb
config/application.rb

RST-3880 Adding flatten to pdf builder

---

spec/support/messaging/et1-v3-en.yml
vendor/assets/pdf_forms/et1-v3-en.yml

RST-3937 ET1 not populating Q1.11

---

Gemfile
Gemfile.lock
app/commands/validate_claimants_file_command.rb
app/controllers/api/v2/base_controller.rb
app/controllers/api/v2/validation_controller.rb
app/validators/claimants_file_validator.rb
app/validators/post_code_validator.rb
app/views/api/v2/validation/validate.json.jbuilder
spec/commands/validate_claimants_file_command_spec.rb
spec/factories/json/json_validate_commands.rb
spec/fixtures/simple_user_with_csv_group_claims_multiple_errors.csv
spec/requests/v2/validate_claimants_file_spec.rb

RST-3853 Validation for et1 group claimants file

---

app/services/claim_claimants_file_importer_service.rb

RST-3774 Group claims upload no longer fails if using empty template

---

spec/factories/json/json_claim_factory.rb
spec/factories/json/json_file_factory.rb
spec/factories/json/json_validate_commands.rb
spec/factories/uploaded_file_factory.rb
spec/requests/v2/create_claim_spec.rb
spec/requests/v2/repair_response_spec.rb
spec/services/uploaded_file_import_service_spec.rb

…onger actively used
```
[ ] Yes
[ ] No
```

RST-1729 - Removed url based uploaded file specs etc... as it is no longer used

---

app/services/claim_claimants_file_importer_service.rb
spec/services/claim_claimants_file_importer_service_spec.rb

RST-4343 CSV importer no longer runs if the claim already has secondary claimants

---

config/environments/production.rb

RST-4578 Now using ACAS V2 by default

---

app/services/claim_claimants_file_importer_service.rb
app/validators/claimants_file_validator.rb
spec/fixtures/simple_user_with_csv_group_claims.csv
spec/requests/v2/create_claim_spec.rb
spec/support/helpers/normalize_csv_data_helper.rb

RST-4341
RST-4341 Claimants file now accepts title in any case and gets converted to Mr, Mrs etc.. before saving
```
[ ] Yes
[X] No
```

RST-4341 Claimants file now accepts title in any case

---

Gemfile.lock
app/commands/create_blob_command.rb
app/controllers/api/v2/blobs_controller.rb
app/controllers/api/v2/create_blobs_controller.rb
app/event_handlers/blob_created_handler.rb
app/services/build_claim_et1_pdf_file_service.rb
app/services/build_claim_et1a_pdf_file_service.rb
app/services/build_claim_pdf_file_service.rb
app/services/concerns/pdf_builder/active_storage.rb
app/services/uploaded_file_allocator_service.rb
app/views/api/v2/create_blobs/create.json.jbuilder
config/initializers/event_handlers.rb
config/routes.rb
spec/commands/build_response_command_spec.rb
spec/event_handlers/blob_built_handler_spec.rb
spec/requests/v2/create_blob_spec.rb
spec/requests/v2/create_claim_spec.rb
spec/requests/v2/create_response_spec.rb
spec/services/uploaded_file_allocator_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-4686
RST-4686 New file upload system
```
[ ] Yes
[ ] No
```

RST-4686 New file upload system

---

Dockerfile.dev
config/application.rb
config/environments/development.rb
config/initializers/sidekiq.rb
config/sidekiq.yml
lib/tasks/configure_azure_storage.rake

RST-4439
```
[ ] Yes
[X] No
```

Changes for use with scaffold

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/development.rb
config/environments/test.rb

This reverts commit 73e1846d169a560b62344f60f556fee1088a68ce.
```
[ ] Yes
[ ] No
```

Revert "Rst4800 (#607)"

---

app/jobs/fetch_acas_certificates_job.rb
vendor/gems/et_acas_api/app/models/et_acas_api/certificate_not_found.rb

RST-4800 Improved error handling

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/development.rb
config/environments/test.rb

https://tools.hmcts.net/jira/browse/RST-4907
Re enables azure insights - works alongside sentry
```
[ ] Yes
[X] No
```

(RST-4907) Re configured azure insights

---

.gitignore
.rubocop.yml
Gemfile
Gemfile.lock
app/event_handlers/response_export_feedback_received_handler.rb
config/initializers/event_handlers.rb
spec/event_handlers/response_export_feedback_received_handler_spec.rb
spec/factories/export_factory.rb

(RST-5218) API Changes to allow auto office allocation for responses

---

app/models/uploaded_file.rb
spec/event_handlers/claim_email_handler_spec.rb

https://tools.hmcts.net/jira/browse/RST-5414
```
[ ] Yes
[X] No
```

(RST-5414) Fixed bug where submission email was sending incorrect file when an rtf file was submitted

---

charts/et-pet-api/values.yaml

(RST-5651) Storage account now based on environment

---

charts/et-pet-api/Chart.yaml
charts/et-pet-api/values.yaml

(RST-5651) Added acas json service url to secrets

---

charts/et-pet-api/Chart.yaml
charts/et-pet-api/values.yaml

(RST-5651) Fixed ingress issues with api and sidekiq

---

charts/et-pet-api/Chart.yaml
charts/et-pet-api/values.yaml

(RST-5651) Changed ingress to internal url

---

Jenkinsfile_CNP

(RST-5651) Removing the directory for fake gov notify before test

---

spec/rails_helper.rb

(RST-5959) Fixed coverage issue

---

db/migrate/20231024153448_remove_pgcrypto.rb
db/schema.rb

(RST-5996) Removed pgcrypto extension - not needed

---

app/validators/claimants_file_validator.rb
config/application.rb
config/environments/production.rb
lib/tasks/test.rake
spec/factories/claimants_file_factory.rb
spec/support/csv_builder.rb
spec/validators/claimants_file_validator_spec.rb

(RST-6003) Validation issues fixed for claimants file

---

Gemfile.lock

(RST-6188) Upgraded puma to address CVE

---

Dockerfile
Dockerfile.development
Gemfile
Gemfile.lock
bin/run_full_system

(RST-6212) Development docker image permission issues fixed
```
[ ] Yes
[ ] No
```

(RST-6212) Full system command now runs invoker instead of foreman.

---

app/validators/claimants_file_validator.rb
spec/validators/claimants_file_validator_spec.rb

(RST-6199) CSV parsing now stripping non breaking space characters (Chr 160 - A0)

---

Gemfile.lock

(RST-6288) Upgraded nokogiri (security issue)

---

app/validators/claimants_file_validator.rb
spec/validators/claimants_file_validator_spec.rb

(RST-6373) Address fields apart from building and post code are now optional in csv import

---

charts/et-pet-api/Chart.yaml
charts/et-pet-api/values.yaml

(RST-6397) Re enable file conversions

---

app/services/build_response_pdf_file_service.rb
app/validators/claimants_file_validator.rb
spec/factories/external_system_factory.rb
spec/factories/json/json_response_factory.rb
spec/support/et_exporter_support/file_objects/et3_pdf_file/acas_section.rb
spec/support/et_exporter_support/file_objects/et3_pdf_file/employment_details_section.rb

(RST-6428) Fixed issue with some et3 questions being pre ticked in the pdf

---

config/application.rb
spec/event_handlers/convert_files_handler_spec.rb
spec/requests/v2/create_claim_spec.rb
spec/requests/v2/repair_response_spec.rb
spec/support/et_exporter_support/exported_data.rb

(RST-6539) Re disabled file conversions

---

Dockerfile
Dockerfile.development
README.md
app/services/build_claim_pdf_file_service.rb
charts/et-pet-api/Chart.yaml
charts/et-pet-api/values.yaml
spec/services/build_claim_pdf_file_service_spec.rb

(RST-6698) Upgraded pdftk

---

.vscode/launch.json
app/commands/build_response_command.rb
app/event_handlers/response_email_handler.rb
app/event_handlers/response_export_feedback_received_handler.rb
app/models/response.rb
app/services/build_response_pdf_file_service.rb
config/initializers/event_handlers.rb
db/seeds.rb
spec/commands/build_response_command_spec.rb
spec/factories/command_factory.rb
spec/requests/v2/create_response_spec.rb
spec/support/et_exporter_support/file_objects/et3_pdf_file/representative_section.rb

(RST-6832) Attempt to run tests - failures locally unexplained

---

Gemfile.lock
app/event_handlers/response_export_feedback_received_handler.rb
spec/event_handlers/response_export_feedback_received_handler_spec.rb

Rst 6901 - Add office fallback lookup for et3 responses
