hmcts/et-pet-api

- app/services/claim_file_builder/build_response_pdf_file.rb
- spec/factories/representative_factory.rb
- spec/factories/respondent_factory.rb
- spec/factories/response_factory.rb
- spec/support/landing_folder_support/file_objects/et3_pdf_file.rb
The PDF file generation for ET3 now fills in all tri state fields correctly (where there is an 'unset' value) when fields are omitted from the front end data (RST-1198)
> PDF File generation now deals with optional data

- app/services/export_service_exporters/response_exporter.rb
- spec/requests/create_response_spec.rb
- spec/services/export_service_spec.rb
The ET3 ETHOS filenames now contain the underscored respondent name (company name)
> RST-1164 ET3 Output Filename Correction

- app/event_handlers/response_created_handler.rb
- app/mailers/response_mailer.rb
- spec/support/email_support/email_objects/new_response_email_html.rb
- spec/support/email_support/email_objects/new_response_email_text.rb
Response mailer now uses email_receipt field from api for the to address
> Response mailer now uses email_receipt field from api for the to address

- Gemfile.lock
Upgraded sprockets to 3.7.2 due to CVE-2018-3760 security issue. Whilst this does not affect our application (as we are not hosting any assets here), it stops github showing a concern about a security issue.
> Upgraded sprockets to 3.7.2 due to CVE-2018-3760 security issue. 

- app/services/export_service_exporters/claim_exporter.rb
- app/services/export_service_exporters/response_exporter.rb
- spec/factories/claimant_factory.rb
- spec/factories/respondent_factory.rb
- spec/factories/xml/xml_claim_factory.rb
- spec/requests/v1/create_claim_spec.rb
- spec/services/export_service_exporters/claim_exporter_spec.rb
- spec/services/export_service_exporters/response_exporter_spec.rb
This PR fixes the issues seen in production yesterday where strange characters in the persons name were coming through to the filename and causing files not to be found.
Now, anything that is classed as white space is converted to an underscore and any other non word characters are removed completely from the filename.
> Claim and response exporter can accept names with non alpha characters

- app/services/export_service_exporters/claim_exporter.rb
- app/services/export_service_exporters/response_exporter.rb
- spec/services/export_service_exporters/claim_exporter_spec.rb
- spec/services/export_service_exporters/response_exporter_spec.rb
Fix for duplicate underscore issue in filenames for claim and response exporter
> Fix for duplicate underscore issue in filenames for claims and responses

- README.md
- app/services/claim_file_builder/build_response_pdf_file.rb
- db/migrate/20180903102740_add_disability_to_respondents.rb
- db/migrate/20180903102828_copy_disability_from_representatives.rb
- db/migrate/20180903104122_drop_disability_from_representatives.rb
- db/structure.sql
- spec/factories/json/json_response_factory.rb
- spec/factories/representative_factory.rb
- spec/factories/respondent_factory.rb
- spec/support/landing_folder_support/file_objects/et3_pdf_file.rb
None
None
- RST-1377 - Breaking Change - Move disability information from representative to the respondent.  This is accompanied by a release of ET3 which will happen at the same time
> Preparation for release 1.4.0 Continued

- app/services/claim_file_builder/render_to_file.rb
- spec/factories/xml/xml_claim_factory.rb
- spec/requests/v1/create_claim_spec.rb
- spec/support/landing_folder_support/file_objects/et1_txt_file.rb
- spec/support/landing_folder_support/file_objects/et1a_txt_file.rb
- spec/support/landing_folder_support/file_objects/et3_txt_file.rb
- spec/support/matchers/have_file_encoding.rb
This PR fixes an issue where if the user enters in any UTF8 characters (such as a posh apostrophe - in this address - St John’s Lane ) - the resulting files would end up as UTF8 and ETHOS importing stopped completely.
> RST-1354 - Encoding Issues

- db/migrate/20180919102125_configure_role_permissions_for_roles.rb
In conjunction with https://github.com/ministryofjustice/et-admin/pull/45 - this migration adds the new permissions for roles to the user roles.
> RST-1314: Generate migration for admin user roles

- app/event_handlers/signed_s3_form_data_created_handler.rb
- spec/requests/v2/create_signed_s3_url_spec.rb
The `key` was cached which presented the opportunity for duplicate upload keys to be used, potentially causing uploaded RTFs to be overwritten.
> RST-1457: Prevent caching of S3 upload signature URLs

- app/services/claim_file_builder/render_to_file.rb
- spec/factories/json/json_claimant_factory.rb
- spec/factories/json/json_respondent_factory.rb
- spec/requests/v2/create_claim_spec.rb
- spec/services/claim_file_builder/build_claim_text_file_spec.rb
Fix bug RST-1477 Some unicode characters could not be converted into windows encoding
This PR changes the render method used for all file output to ATOS - specifying that any unknown characters will get removed rather than raising an exception
> Fix bug RST-1477

- db/migrate/20181031123357_fix_default_employment_details.rb
- db/migrate/20181031123747_update_default_employment_details.rb
There is an error in the default value for the `employment_details` section of a `Claim`. The default value is currently `"{}"` which is a string of empty hash notation as opposed to an empty hash itself. This PR sets the default value to `{}` from this point onwards and also migrates existing instances of `"{}"` to `{}`.
This then enables an ActiveRecord query to be run which checks if the `employment_details` section of a `Claim` is `.empty?`, which will be used to provide a data extraction for RST-1483.
> RST-1483: Migrate employment_details Default and Existing Values

- db/seeds.rb
Full system currently can't build offices properly as the API seeding task is ordered incorrectly. This would be an issue in prod or anywhere else if we ran a seeding task when deploying.
> RST-1583: Change seed task order

- app/models/claim.rb
- app/services/claim_claimants_file_importer_service.rb
- spec/factories/json/json_claim_factory.rb
- spec/factories/json/json_file_factory.rb
- spec/requests/v2/create_claim_spec.rb
- vendor/gems/et_atos_export/app/event_handlers/et_atos_export/export_claim_handler.rb
This PR fixes a bug raised in RST-1674 where if a user were to send a filename with the file extension uppercased, the system would not find the RTF or CSV file in ET1.
This is not an issue with ET3 as the file transfer mechanism is different and that doesnt send the uppercased extension
> RST-1674 - Case insensitive filenames

- app/services/claim_claimants_file_importer_service.rb
- spec/factories/uploaded_file_factory.rb
- spec/fixtures/simple_user_with_csv_group_claims_bad_encoding.csv
- spec/services/claim_claimants_file_importer_service_spec.rb
- spec/support/helpers/normalize_csv_data_helper.rb
RST-1711 API - Live Issue - CSV file was failing due to invalid utf8 content - code will now convert to utf8, ignoring any weird characters that it cannot convert
> RST-1711 API - Live Issue - CSV file was failing

- app/services/direct_upload_into_collection_service.rb
- spec/documentation/build_blob_amazon_spec.rb
- spec/documentation/build_blob_azure_spec.rb
- spec/documentation/create_signed_s3_url_spec.rb
- spec/factories/json/json_response_factory.rb
- spec/models/exported_file_spec.rb
- spec/models/response_spec.rb
- spec/models/uploaded_file_spec.rb
- spec/requests/v2/build_blob_spec.rb
- spec/requests/v2/create_response_spec.rb
- spec/requests/v2/create_signed_s3_url_spec.rb
- spec/services/uploaded_file_allocator_service_spec.rb
- spec/support/setup_azure_blob_containers.rb
- spec/support/setup_s3_buckets.rb
- spec/support/shared_contexts/with_cloud_provider_switching.rb
This PR allows the et3 submission end point to work in azure mode - so when in azure mode, it gets the source file from azure direct upload location and saves a copy in the azure active storage location ready for use by the rest of the application
> Rst 1717 et3 ai endpoint

- Gemfile
- Gemfile.lock
- Procfile
- config/puma.rb
- config/unicorn.rb
- run.sh
This PR configures our web server to use puma instead of unicorn.
This was trialled in the dev environment in order to gain performance improvement figures and it si estimated to be maybe 30% faster.
The main reason for using it is so that when a slow external request in the API (currently only the acas certificate lookup) is in progress - it does not tie up a whole worker - instead just one thread in a worker - hopefully reducing client side timeouts in et1 application
> Trying puma

- app/event_handlers/prepare_response_handler.rb
- config/initializers/event_handlers.rb
- vendor/gems/et_s3_to_azure/lib/rails/commands/azure_import/azure_import_command.rb
This PR changes the way the response mailer is hooked into the system. 
Before, the email was sent inline as part of the 'Response Preparation' which meant it went to try and read the pdf file literally about 6 mSec after it had written it.  My guess is that the blob service hadn't actually stored it by the time we went to read it.
So, I have removed the mailer from here - which makes more sense as the 'Response Preparation' does not really include sending a mail - the sending of the mail should happen after response preparation.
I have ran this through full system and got no errors
> RST-1824 - Mailer using file before it was ready

- app/commands/build_claim_command.rb
- app/commands/create_claim_command.rb
- app/commands/pre_allocate_pdf_file_command.rb
- app/services/build_claim_pdf_file_service.rb
- spec/commands/build_claim_command_spec.rb
- spec/commands/create_claim_command_spec.rb
- spec/commands/pre_allocate_pdf_file_command_spec.rb
- spec/factories/claim_factory.rb
- spec/requests/v2/import_claim_spec.rb
- spec/services/build_claim_pdf_file_service_spec.rb
This PR solves a problem where the internal filename used for the customer's pdf's was simply et1_atos_export.pdf - so admin users would have had problems if downloading them as they wouldnt know from the filenames what they were.
The reason for this is that the 'pre allocation' of the pdf url was done at an early stage in the command chain, before the primary claimant was known.
This change adds an extra command on to the end of the chain to pre allocate the url - then fixes the actual file name generation in the pdf service
> RST-1831 Internal pdf file has incorrect filename

- config/environments/production.rb
This PR allows configuration of the raven client to allow SSL certificate verification to be disabled by setting RAVEN_SSL_VERIFICATION=false as an environment variable (defaults to true)
> SSL Certificate Verification Control 

- app/commands/build_response_command.rb
- db/migrate/20190524080441_change_precision_of_queried_hours_in_responses.rb
- db/structure.sql
- spec/commands/build_response_command_spec.rb
- spec/factories/json/json_response_factory.rb
- spec/requests/v2/create_response_spec.rb
This PR fixes the API side of RST-1926 - i.e. the API protects itself from error.
It increases the column side for queried_hours which was precision 4, scale 2 - i.e. xx.yy - now increased
to precision 5, scale 2 - i.e. xxx.yy - as the maximum hours per week is 164
Added validation to the build response command to prevent values greater than 164 or less than or equal to zero
> RST-1926-queried-hours

- Gemfile
- Gemfile.lock
- app/controllers/concerns/cache_command_results.rb
- app/event_handlers/claim_export_handler.rb
- app/models/export.rb
- db/migrate/20190618145253_add_export_queue_to_external_systems.rb
- db/migrate/20190618153701_add_ccd_manchester_external_system.rb
- db/migrate/20190705075853_add_country_to_addresses.rb
- db/seeds.rb
- db/structure.sql
- spec/factories/claimant_factory.rb
- spec/factories/external_system_factory.rb
- spec/factories/json/json_address_factory.rb
- spec/factories/json/json_claim_factory.rb
- spec/factories/json/json_claimant_factory.rb
- spec/support/sidekiq.rb
https://tools.hmcts.net/jira/browse/RST-1930
This PR introduces a new gem called et_exporter which hooks itself in to the API's event system.
As standard, nothing will change - until you go into the admin and enable 'Export' for the externla system named 'CCD Manchester' (this is just for trial purposes and WILL go into production - as they need production data going into CCD fairly soon).
```
[ ] Yes
[X] No
```
> Rst 1930 ccd export

- Gemfile
- Gemfile.lock
- db/migrate/20190618153701_add_ccd_manchester_external_system.rb
- db/migrate/20190718073101_add_multiples_to_ccd_manchester_external_system.rb
- db/seeds.rb
RST-1935
This PR uses a later version of et exporter to add the content type to the exported data for all uploaded files
```
[ ] Yes
[X] No
```
> Et exporter gem now adds content_type to the uploaded files

- app/event_handlers/blob_built_handler.rb
- config/database.yml
- spec/requests/v2/build_blob_spec.rb
RST-2425
RST-2425 - Bug fix - the blob built handler was incorrectly using the standard azure blob storage container instead of the direct upload one
```
[ ] Yes
[X] No
```
> RST-2425 - Bug fix - incorrect container used for et3 file upload

- app/commands/build_claim_command.rb
- app/event_handlers/claim_email_handler.rb
- app/mailers/claim_mailer.rb
- app/models/uploaded_file.rb
- app/views/mailers/claim_mailer/confirmation_email.et1-v1-cy.html.erb
- app/views/mailers/claim_mailer/confirmation_email.et1-v1-cy.text.erb
- app/views/mailers/claim_mailer/confirmation_email.et1-v1-en.html.erb
- app/views/mailers/claim_mailer/confirmation_email.et1-v1-en.text.erb
- config/initializers/event_handlers.rb
- config/locales/cy.yml
- db/migrate/20200312133758_add_email_template_reference_to_claims.rb
- db/migrate/20200312134523_add_confirmation_email_recipients_to_claims.rb
- db/schema.rb
- docker/dev/docker-compose.yml
- spec/factories/json/json_claim_factory.rb
- spec/requests/v2/create_claim_spec.rb
- spec/support/email_support/email_objects/new_claim_email_cy_html.rb
- spec/support/email_support/email_objects/new_claim_email_cy_text.rb
- spec/support/email_support/email_objects/new_claim_email_en_html.rb
- spec/support/email_support/email_objects/new_claim_email_en_text.rb
- spec/support/email_support/emails_sent.rb
- spec/support/helpers/claim_helper.rb
- spec/support/messaging.rb
- spec/support/messaging/cy-dates.yml
- spec/support/messaging/cy.yml
- spec/support/messaging/en.yml
https://tools.hmcts.net/jira/browse/RST-1439
This PR adds the API side to RST-1439 which is sending the claimant confirmation email with template selectable by the caller (ET1) to allow for multiple languages
```
[ ] Yes
[X] No
```
This change should be deployed before the ET1 change of the same branch.  Running this with older versions of ET1 will work fine.
> RST-1439 ET1 (Azure) Move confirmation email into API

- app/services/build_claim_pdf_file_service.rb
- db/schema.rb
- docker/dev/docker-compose.yml
- spec/factories/json/json_claim_factory.rb
- spec/requests/v2/create_claim_spec.rb
- spec/support/messaging/cy.yml
- spec/support/messaging/en.yml
RST-1891
This PR fixes a bug when the API generates its own PDF (will be enabled soon as other tickets need it) - the field for 'Worked notice period or paid in lieu' was not sent to the pdf
```
[ ] Yes
[X] No
```
> RST-1891 API Missing fields in pdf generation

- app/models/claim.rb
- app/services/build_claim_pdf_file_service.rb
- spec/support/email_support/email_objects/new_claim_email_cy_html.rb
- spec/support/helpers/office_helper.rb
- spec/support/landing_folder_support/file_objects/et1_pdf_file.rb
- spec/support/landing_folder_support/file_objects/et1_pdf_file/official_use_only_section.rb
- spec/support/messaging/cy.yml
- spec/support/messaging/en.yml
- vendor/assets/pdf_forms/et1-v1-cy.yml
- vendor/assets/pdf_forms/et1-v1-en.yml
https://tools.hmcts.net/jira/browse/RST-2578
This PR adds the office name and the submission date to the PDF's generated by the API
```
[ ] Yes
[X] No
```
> RST-2578 (API) New pdf generation code was missing 2 fields

- app/views/mailers/claim_mailer/confirmation_email.et1-v1-cy.html.erb
- app/views/mailers/claim_mailer/confirmation_email.et1-v1-cy.text.erb
- app/views/mailers/claim_mailer/confirmation_email.et1-v1-en.html.erb
- app/views/mailers/claim_mailer/confirmation_email.et1-v1-en.text.erb
- spec/support/email_support/email_objects/new_claim_email_en_html.rb
- spec/support/email_support/email_objects/new_claim_email_en_text.rb
https://tools.hmcts.net/jira/browse/RST-2009
As part of RST-2009 - this PR changes from using the application reference number to the fee group reference number in the ET1 email template
```
[ ] Yes
[X] No
```
> RST-2009 Change claim number on ET1 email

- app/services/build_claim_pdf_file_service.rb
https://tools.hmcts.net/jira/browse/RST-2820
This PR allows for the negative spacing bug when postcodes without spaces are used
```
[ ] Yes
[X] No
```
> RST-2820 ET1 Pdf form not created in Admin

- app/commands/build_claim_command.rb
- app/event_handlers/claim_pdf_file_handler.rb
- app/services/build_claim_pdf_file_service.rb
- app/services/concerns/pdf_builder/base.rb
- app/services/concerns/pdf_builder/multi_template.rb
- db/migrate/20201012111151_add_time_zone_to_claims.rb
- db/schema.rb
- spec/factories/claim_factory.rb
- spec/factories/json/json_claim_factory.rb
- spec/services/build_claim_pdf_file_service_spec.rb
- spec/support/landing_folder_support/file_objects/et1_pdf_file/official_use_only_section.rb
https://tools.hmcts.net/jira/browse/RST-2904
RST-2904 Time zone is now part of the api call with a default of 'London' - it is also stored in the claim and used by pdf generation for the date
```
[ ] Yes
[X] No
```
> RST-2904 Time zone is now part of the api call

- app/commands/rebuild_representative_command.rb
- app/commands/rebuild_respondent_command.rb
- app/commands/rebuild_response_additional_information_file_command.rb
- app/commands/rebuild_response_command.rb
- app/commands/recreate_response_command.rb
- app/commands/repair_response_command.rb
- app/controllers/api/v2/respondents/repair_responses_controller.rb
- app/event_handlers/repair_uploaded_files_handler.rb
- app/event_handlers/reprepare_response_handler.rb
- app/event_handlers/response_repair_requested_handler.rb
- app/models/claim.rb
- app/models/command.rb
- app/models/event.rb
- app/models/response.rb
- app/models/uploaded_file.rb
- app/views/api/v2/respondents/repair_responses/create.json.jbuilder
- config/initializers/event_handlers.rb
- config/routes.rb
- db/migrate/20201013060132_repopulate_missing_et3_rtf_files_from1409.rb
- db/migrate/20201030081306_migrate_commands_with_no_root_object.rb
- db/schema.rb
- spec/factories/command_factory.rb
- spec/factories/json/json_response_factory.rb
- spec/factories/response_factory.rb
- spec/factories/uploaded_file_factory.rb
- spec/fixtures/et3.txt
- spec/requests/v2/repair_response_spec.rb
- vendor/gems/et_atos_export/app/services/et_atos_export/response_file_builder/build_response_rtf_file.rb
- vendor/gems/et_atos_export/app/services/et_atos_export/response_file_builder/build_response_text_file.rb
This PR adds a command to the API to attempt the repair of damaged ET3 responses - i.e. where the files have been lost or never imported etc..
```
[ ] Yes
[X] No
```
> Rst 2905 ET3 Repair functionality

- app/jobs/assign_root_object_to_commands_job.rb
- config/schedule.yml
- db/migrate/20201030081306_migrate_commands_with_no_root_object.rb
- db/migrate/20201113104003_migrate_commands_with_no_root_object_again.rb
RST-2905 Removed migrations for  commands with no root object - now done in a background job
```
[ ] Yes
[X] No
```
> RST-2905 Removed migrations for  commands with no root object

- app/services/claim_claimants_file_importer_service.rb
- spec/factories/uploaded_file_factory.rb
- spec/fixtures/simple_user_with_csv_group_claims_with_spaces.csv
- spec/services/claim_claimants_file_importer_service_spec.rb
- spec/support/helpers/normalize_csv_data_helper.rb
https://tools.hmcts.net/jira/browse/RST-3311
RST-3311 (ECM) CSV importer now removes spaces from all values before entry into the system
```
[ ] Yes
[X] No
```
> RST-3311 (ECM) CSV importer now removes spaces from all values

- db/migrate/20220826103604_add_offices_for_reform_claims.rb
- db/offices.csv
- db/schema.rb
- spec/services/office_service_spec.rb
https://tools.hmcts.net/jira/browse/RST-4618
This change allows all office codes beginning with '6' to be mapped to the Leeds office and any beginning with '8' to be mapped to the Glasgow office
```
[ ] Yes
[X] No
```
> Rst 4618 - Allowing reform offices to be mapped to correct place

- config/initializers/mime_types.rb
- spec/requests/v2/create_blob_spec.rb
https://tools.hmcts.net/jira/browse/RST-5002
This PR adds the mime type application/csv so that it equals 'text/csv' - this was causing csv files to fail to be identified properly
```
[ ] Yes
[X] No
```
> (RST-5002) Added application/csv mime type to registry

- db/offices.csv
- db/seeds.rb
- spec/services/office_service_spec.rb
This PR updates the seed data which is only used in et-full-system testing - the update is to allow the 2 special offices (60 and 80) to 'export' responses.
Even though nothing will be exported, the plan is to configure the et_ccd_exporter to find the claim that the response is for from ccd, then change the office for the response (via an async sidekiq job) accordingly
```
[ ] Yes
[X] No
```
> (RST-5254) Seed data update for RST-5218
